// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: answer.proto

package serverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Операции над входной строкой
type Operation int32

const (
	Operation_OP_UNSPECIFIED Operation = 0
	Operation_OP_UPPER       Operation = 1
	Operation_OP_LOWER       Operation = 2
	Operation_OP_REVERSE     Operation = 3
	Operation_OP_BASE64      Operation = 4
	Operation_OP_SHA256      Operation = 5
	Operation_OP_COUNT_WORDS Operation = 6
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "OP_UNSPECIFIED",
		1: "OP_UPPER",
		2: "OP_LOWER",
		3: "OP_REVERSE",
		4: "OP_BASE64",
		5: "OP_SHA256",
		6: "OP_COUNT_WORDS",
	}
	Operation_value = map[string]int32{
		"OP_UNSPECIFIED": 0,
		"OP_UPPER":       1,
		"OP_LOWER":       2,
		"OP_REVERSE":     3,
		"OP_BASE64":      4,
		"OP_SHA256":      5,
		"OP_COUNT_WORDS": 6,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_answer_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_answer_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{0}
}

// Задача: операция + входные данные
type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // для логов/трассировки
	Operation     Operation              `protobuf:"varint,2,opt,name=operation,proto3,enum=task.Operation" json:"operation,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // исходные данные
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_answer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TaskRequest) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_OP_UNSPECIFIED
}

func (x *TaskRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// Результат
type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                    // если ok=false
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`                                  // результат преобразования
	ProcessingNs  int64                  `protobuf:"varint,5,opt,name=processing_ns,json=processingNs,proto3" json:"processing_ns,omitempty"` // время обработки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_answer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TaskResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *TaskResponse) GetProcessingNs() int64 {
	if x != nil {
		return x.ProcessingNs
	}
	return 0
}

var File_answer_proto protoreflect.FileDescriptor

const file_answer_proto_rawDesc = "" +
	"\n" +
	"\fanswer.proto\x12\x04task\"u\n" +
	"\vTaskRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12-\n" +
	"\toperation\x18\x02 \x01(\x0e2\x0f.task.OperationR\toperation\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"\x90\x01\n" +
	"\fTaskResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12#\n" +
	"\rprocessing_ns\x18\x05 \x01(\x03R\fprocessingNs*}\n" +
	"\tOperation\x12\x12\n" +
	"\x0eOP_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bOP_UPPER\x10\x01\x12\f\n" +
	"\bOP_LOWER\x10\x02\x12\x0e\n" +
	"\n" +
	"OP_REVERSE\x10\x03\x12\r\n" +
	"\tOP_BASE64\x10\x04\x12\r\n" +
	"\tOP_SHA256\x10\x05\x12\x12\n" +
	"\x0eOP_COUNT_WORDS\x10\x062\xb4\x01\n" +
	"\vTaskService\x120\n" +
	"\aProcess\x12\x11.task.TaskRequest\x1a\x12.task.TaskResponse\x128\n" +
	"\rProcessStream\x12\x11.task.TaskRequest\x1a\x12.task.TaskResponse0\x01\x129\n" +
	"\fProcessBatch\x12\x11.task.TaskRequest\x1a\x12.task.TaskResponse(\x010\x01B\x17Z\x15grpctask/proto;taskpbb\x06proto3"

var (
	file_answer_proto_rawDescOnce sync.Once
	file_answer_proto_rawDescData []byte
)

func file_answer_proto_rawDescGZIP() []byte {
	file_answer_proto_rawDescOnce.Do(func() {
		file_answer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_answer_proto_rawDesc), len(file_answer_proto_rawDesc)))
	})
	return file_answer_proto_rawDescData
}

var file_answer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_answer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_answer_proto_goTypes = []any{
	(Operation)(0),       // 0: task.Operation
	(*TaskRequest)(nil),  // 1: task.TaskRequest
	(*TaskResponse)(nil), // 2: task.TaskResponse
}
var file_answer_proto_depIdxs = []int32{
	0, // 0: task.TaskRequest.operation:type_name -> task.Operation
	1, // 1: task.TaskService.Process:input_type -> task.TaskRequest
	1, // 2: task.TaskService.ProcessStream:input_type -> task.TaskRequest
	1, // 3: task.TaskService.ProcessBatch:input_type -> task.TaskRequest
	2, // 4: task.TaskService.Process:output_type -> task.TaskResponse
	2, // 5: task.TaskService.ProcessStream:output_type -> task.TaskResponse
	2, // 6: task.TaskService.ProcessBatch:output_type -> task.TaskResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_answer_proto_init() }
func file_answer_proto_init() {
	if File_answer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_answer_proto_rawDesc), len(file_answer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_answer_proto_goTypes,
		DependencyIndexes: file_answer_proto_depIdxs,
		EnumInfos:         file_answer_proto_enumTypes,
		MessageInfos:      file_answer_proto_msgTypes,
	}.Build()
	File_answer_proto = out.File
	file_answer_proto_goTypes = nil
	file_answer_proto_depIdxs = nil
}
