// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/api/api_service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_api_api_service_proto protoreflect.FileDescriptor

const file_proto_api_api_service_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/api/api_service.proto\x12\x14logcounter.proto.api\x1a\x18proto/api/messages.proto2\xac\x01\n" +
	"\n" +
	"MapService\x12M\n" +
	"\x04Init\x12!.logcounter.proto.api.InitRequest\x1a\".logcounter.proto.api.InitResponse\x12O\n" +
	"\x06DoTask\x12!.logcounter.proto.api.TaskRequest\x1a\".logcounter.proto.api.TaskResponse2d\n" +
	"\rReduceService\x12S\n" +
	"\x06Reduce\x12#.logcounter.proto.api.ReduceRequest\x1a$.logcounter.proto.api.ReduceResponseB\x19Z\x17logcounter/grpc/api;apib\x06proto3"

var file_proto_api_api_service_proto_goTypes = []any{
	(*InitRequest)(nil),    // 0: logcounter.proto.api.InitRequest
	(*TaskRequest)(nil),    // 1: logcounter.proto.api.TaskRequest
	(*ReduceRequest)(nil),  // 2: logcounter.proto.api.ReduceRequest
	(*InitResponse)(nil),   // 3: logcounter.proto.api.InitResponse
	(*TaskResponse)(nil),   // 4: logcounter.proto.api.TaskResponse
	(*ReduceResponse)(nil), // 5: logcounter.proto.api.ReduceResponse
}
var file_proto_api_api_service_proto_depIdxs = []int32{
	0, // 0: logcounter.proto.api.MapService.Init:input_type -> logcounter.proto.api.InitRequest
	1, // 1: logcounter.proto.api.MapService.DoTask:input_type -> logcounter.proto.api.TaskRequest
	2, // 2: logcounter.proto.api.ReduceService.Reduce:input_type -> logcounter.proto.api.ReduceRequest
	3, // 3: logcounter.proto.api.MapService.Init:output_type -> logcounter.proto.api.InitResponse
	4, // 4: logcounter.proto.api.MapService.DoTask:output_type -> logcounter.proto.api.TaskResponse
	5, // 5: logcounter.proto.api.ReduceService.Reduce:output_type -> logcounter.proto.api.ReduceResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_api_api_service_proto_init() }
func file_proto_api_api_service_proto_init() {
	if File_proto_api_api_service_proto != nil {
		return
	}
	file_proto_api_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_api_service_proto_rawDesc), len(file_proto_api_api_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_api_api_service_proto_goTypes,
		DependencyIndexes: file_proto_api_api_service_proto_depIdxs,
	}.Build()
	File_proto_api_api_service_proto = out.File
	file_proto_api_api_service_proto_goTypes = nil
	file_proto_api_api_service_proto_depIdxs = nil
}
