// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/api/messages.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatusResponse reports the outcome of an RPC.
type StatusResponse int32

const (
	StatusResponse_Ok      StatusResponse = 0
	StatusResponse_Warning StatusResponse = 1
	StatusResponse_Error   StatusResponse = 2
)

// Enum value maps for StatusResponse.
var (
	StatusResponse_name = map[int32]string{
		0: "Ok",
		1: "Warning",
		2: "Error",
	}
	StatusResponse_value = map[string]int32{
		"Ok":      0,
		"Warning": 1,
		"Error":   2,
	}
)

func (x StatusResponse) Enum() *StatusResponse {
	p := new(StatusResponse)
	*p = x
	return p
}

func (x StatusResponse) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusResponse) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_messages_proto_enumTypes[0].Descriptor()
}

func (StatusResponse) Type() protoreflect.EnumType {
	return &file_proto_api_messages_proto_enumTypes[0]
}

func (x StatusResponse) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusResponse.Descriptor instead.
func (StatusResponse) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_messages_proto_rawDescGZIP(), []int{0}
}

// TaskType selects the operation to run over a file.
type TaskType int32

const (
	TaskType_COUNT_WORDS       TaskType = 0
	TaskType_COUNT_OCCURRENCES TaskType = 1
	TaskType_COUNT_LINES       TaskType = 2
	TaskType_COUNT_CHARS       TaskType = 3
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "COUNT_WORDS",
		1: "COUNT_OCCURRENCES",
		2: "COUNT_LINES",
		3: "COUNT_CHARS",
	}
	TaskType_value = map[string]int32{
		"COUNT_WORDS":       0,
		"COUNT_OCCURRENCES": 1,
		"COUNT_LINES":       2,
		"COUNT_CHARS":       3,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_messages_proto_enumTypes[1].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_proto_api_messages_proto_enumTypes[1]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_messages_proto_rawDescGZIP(), []int{1}
}

// HostInfo carries everything needed to connect to a host and how many free
// handlers (execution slots) it currently has available.
type HostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	FreeHandlers  uint32                 `protobuf:"varint,4,opt,name=free_handlers,json=freeHandlers,proto3" json:"free_handlers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_proto_api_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_proto_api_messages_proto_rawDescGZIP(), []int{0}
}

func (x *HostInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HostInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HostInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HostInfo) GetFreeHandlers() uint32 {
	if x != nil {
		return x.FreeHandlers
	}
	return 0
}

// InitRequest registers a host together with its available handlers.
type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          []*HostInfo            `protobuf:"bytes,1,rep,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_proto_api_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_messages_proto_rawDescGZIP(), []int{1}
}

func (x *InitRequest) GetHost() []*HostInfo {
	if x != nil {
		return x.Host
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusResponse         `protobuf:"varint,1,opt,name=status,proto3,enum=logcounter.proto.api.StatusResponse" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_proto_api_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_messages_proto_rawDescGZIP(), []int{2}
}

func (x *InitResponse) GetStatus() StatusResponse {
	if x != nil {
		return x.Status
	}
	return StatusResponse_Ok
}

// TaskRequest describes a unit of work: a file path and the task to run on it.
type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Task          TaskType               `protobuf:"varint,2,opt,name=task,proto3,enum=logcounter.proto.api.TaskType" json:"task,omitempty"`
	Word          string                 `protobuf:"bytes,3,opt,name=word,proto3" json:"word,omitempty"` // target word for COUNT_OCCURRENCES
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_api_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_messages_proto_rawDescGZIP(), []int{3}
}

func (x *TaskRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *TaskRequest) GetTask() TaskType {
	if x != nil {
		return x.Task
	}
	return TaskType_COUNT_WORDS
}

func (x *TaskRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

// TaskResponse is the numeric result of a task and its execution status.
type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Status        StatusResponse         `protobuf:"varint,2,opt,name=status,proto3,enum=logcounter.proto.api.StatusResponse" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_proto_api_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_messages_proto_rawDescGZIP(), []int{4}
}

func (x *TaskResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *TaskResponse) GetStatus() StatusResponse {
	if x != nil {
		return x.Status
	}
	return StatusResponse_Ok
}

// MapEntry is one key/value pair produced by a map function, tagged with the
// type of function that produced it.
type MapEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	FunctionType  string                 `protobuf:"bytes,3,opt,name=function_type,json=functionType,proto3" json:"function_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapEntry) Reset() {
	*x = MapEntry{}
	mi := &file_proto_api_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapEntry) ProtoMessage() {}

func (x *MapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapEntry.ProtoReflect.Descriptor instead.
func (*MapEntry) Descriptor() ([]byte, []int) {
	return file_proto_api_messages_proto_rawDescGZIP(), []int{5}
}

func (x *MapEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MapEntry) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MapEntry) GetFunctionType() string {
	if x != nil {
		return x.FunctionType
	}
	return ""
}

// ReduceRequest carries the map to aggregate.
type ReduceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*MapEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReduceRequest) Reset() {
	*x = ReduceRequest{}
	mi := &file_proto_api_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceRequest) ProtoMessage() {}

func (x *ReduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceRequest.ProtoReflect.Descriptor instead.
func (*ReduceRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ReduceRequest) GetEntries() []*MapEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// ReduceResponse is the aggregated numeric result and its execution status.
type ReduceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Status        StatusResponse         `protobuf:"varint,2,opt,name=status,proto3,enum=logcounter.proto.api.StatusResponse" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReduceResponse) Reset() {
	*x = ReduceResponse{}
	mi := &file_proto_api_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceResponse) ProtoMessage() {}

func (x *ReduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceResponse.ProtoReflect.Descriptor instead.
func (*ReduceResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_messages_proto_rawDescGZIP(), []int{7}
}

func (x *ReduceResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ReduceResponse) GetStatus() StatusResponse {
	if x != nil {
		return x.Status
	}
	return StatusResponse_Ok
}

var File_proto_api_messages_proto protoreflect.FileDescriptor

const file_proto_api_messages_proto_rawDesc = "" +
	"\n" +
	"\x18proto/api/messages.proto\x12\x14logcounter.proto.api\"g\n" +
	"\bHostInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12#\n" +
	"\rfree_handlers\x18\x04 \x01(\rR\ffreeHandlers\"A\n" +
	"\vInitRequest\x122\n" +
	"\x04host\x18\x01 \x03(\v2\x1e.logcounter.proto.api.HostInfoR\x04host\"L\n" +
	"\fInitResponse\x12<\n" +
	"\x06status\x18\x01 \x01(\x0e2$.logcounter.proto.api.StatusResponseR\x06status\"r\n" +
	"\vTaskRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x122\n" +
	"\x04task\x18\x02 \x01(\x0e2\x1e.logcounter.proto.api.TaskTypeR\x04task\x12\x12\n" +
	"\x04word\x18\x03 \x01(\tR\x04word\"d\n" +
	"\fTaskResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x03R\x06result\x12<\n" +
	"\x06status\x18\x02 \x01(\x0e2$.logcounter.proto.api.StatusResponseR\x06status\"W\n" +
	"\bMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\x12#\n" +
	"\rfunction_type\x18\x03 \x01(\tR\ffunctionType\"I\n" +
	"\rReduceRequest\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.logcounter.proto.api.MapEntryR\aentries\"f\n" +
	"\x0eReduceResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x03R\x06result\x12<\n" +
	"\x06status\x18\x02 \x01(\x0e2$.logcounter.proto.api.StatusResponseR\x06status*0\n" +
	"\x0eStatusResponse\x12\x06\n" +
	"\x02Ok\x10\x00\x12\v\n" +
	"\aWarning\x10\x01\x12\t\n" +
	"\x05Error\x10\x02*T\n" +
	"\bTaskType\x12\x0f\n" +
	"\vCOUNT_WORDS\x10\x00\x12\x15\n" +
	"\x11COUNT_OCCURRENCES\x10\x01\x12\x0f\n" +
	"\vCOUNT_LINES\x10\x02\x12\x0f\n" +
	"\vCOUNT_CHARS\x10\x03B\x19Z\x17logcounter/grpc/api;apib\x06proto3"

var (
	file_proto_api_messages_proto_rawDescOnce sync.Once
	file_proto_api_messages_proto_rawDescData []byte
)

func file_proto_api_messages_proto_rawDescGZIP() []byte {
	file_proto_api_messages_proto_rawDescOnce.Do(func() {
		file_proto_api_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_messages_proto_rawDesc), len(file_proto_api_messages_proto_rawDesc)))
	})
	return file_proto_api_messages_proto_rawDescData
}

var file_proto_api_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_api_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_api_messages_proto_goTypes = []any{
	(StatusResponse)(0),    // 0: logcounter.proto.api.StatusResponse
	(TaskType)(0),          // 1: logcounter.proto.api.TaskType
	(*HostInfo)(nil),       // 2: logcounter.proto.api.HostInfo
	(*InitRequest)(nil),    // 3: logcounter.proto.api.InitRequest
	(*InitResponse)(nil),   // 4: logcounter.proto.api.InitResponse
	(*TaskRequest)(nil),    // 5: logcounter.proto.api.TaskRequest
	(*TaskResponse)(nil),   // 6: logcounter.proto.api.TaskResponse
	(*MapEntry)(nil),       // 7: logcounter.proto.api.MapEntry
	(*ReduceRequest)(nil),  // 8: logcounter.proto.api.ReduceRequest
	(*ReduceResponse)(nil), // 9: logcounter.proto.api.ReduceResponse
}
var file_proto_api_messages_proto_depIdxs = []int32{
	2, // 0: logcounter.proto.api.InitRequest.host:type_name -> logcounter.proto.api.HostInfo
	0, // 1: logcounter.proto.api.InitResponse.status:type_name -> logcounter.proto.api.StatusResponse
	1, // 2: logcounter.proto.api.TaskRequest.task:type_name -> logcounter.proto.api.TaskType
	0, // 3: logcounter.proto.api.TaskResponse.status:type_name -> logcounter.proto.api.StatusResponse
	7, // 4: logcounter.proto.api.ReduceRequest.entries:type_name -> logcounter.proto.api.MapEntry
	0, // 5: logcounter.proto.api.ReduceResponse.status:type_name -> logcounter.proto.api.StatusResponse
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_api_messages_proto_init() }
func file_proto_api_messages_proto_init() {
	if File_proto_api_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_messages_proto_rawDesc), len(file_proto_api_messages_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_api_messages_proto_goTypes,
		DependencyIndexes: file_proto_api_messages_proto_depIdxs,
		EnumInfos:         file_proto_api_messages_proto_enumTypes,
		MessageInfos:      file_proto_api_messages_proto_msgTypes,
	}.Build()
	File_proto_api_messages_proto = out.File
	file_proto_api_messages_proto_goTypes = nil
	file_proto_api_messages_proto_depIdxs = nil
}
